name: tag_play
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  storage_repository:
    path: packages/storage_repository  
  
  mime: ^2.0.0
  # https://pub.dev/packages/mime
  hive: ^2.2.3
  # https://pub.dev/packages/hive
  dio: ^5.8.0+1
  # https://pub.dev/packages/dio
  bloc: ^9.0.0
  # https://pub.dev/packages/bloc
  intl: ^0.20.2
  # https://pub.dev/packages/intl
  uuid: ^4.5.1
  # https://pub.dev/packages/uuid
  formz: ^0.8.0
  # https://pub.dev/packages/formz
  get_it: ^8.2.0
  # https://pub.dev/packages/get_it  
  chewie: ^1.12.1
  # https://pub.dev/packages/chewie
  freezed: ^3.2.0
  # https://pub.dev/packages/freezed
  shimmer: ^3.0.0
  # https://pub.dev/packages/shimmer
  equatable: ^2.0.7
  # https://pub.dev/packages/equatable
  go_router: ^16.1.0
  # https://pub.dev/packages/go_router
  flutter_svg: ^2.2.0
  # https://pub.dev/packages/flutter_svg
  nfc_manager: ^4.0.2
  # https://pub.dev/packages/nfc_manager
  flow_builder: ^0.1.0
  # https://pub.dev/packages/flow_builder 
  file_picker: ^10.2.1
  # https://pub.dev/packages/file_picker
  hive_flutter: ^1.1.0
  # https://pub.dev/packages/hive_flutter
  flutter_bloc: ^9.1.1
  # https://pub.dev/packages/flutter_bloc
  video_player: ^2.10.0
  # https://pub.dev/packages/video_player
  path_provider: ^2.1.5
  # https://pub.dev/packages/path_provider
  video_compress: ^3.1.4
  # https://pub.dev/packages/video_compress
  cupertino_icons: ^1.0.8

  # flutter_nfc_kit: ^3.6.0
  # https://pub.dev/packages/flutter_nfc_kit

  firebase_core: ^4.0.0
  # https://pub.dev/packages/firebase_core
  json_annotation: ^4.9.0 
  # https://pub.dev/packages/json_annotation
  nfc_manager_ndef: ^1.0.1
  # https://pub.dev/packages/nfc_manager_ndef
  permission_handler: ^12.0.1
  # https://pub.dev/packages/permission_handler
  cached_network_image: ^3.4.1
  # https://pub.dev/packages/cached_network_image
  font_awesome_flutter: ^10.9.0
  # https://pub.dev/packages/font_awesome_flutter
  flutter_image_compress: ^2.4.0
  # https://pub.dev/packages/flutter_image_compress
  shorebird_code_push: ^2.0.4
  image_picker: ^1.2.0
  # https://pub.dev/packages/flutter_image_compress
  iconsax_linear: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  #
  mocktail: ^1.0.4
  # https://pub.dev/packages/mocktail
  bloc_test: ^10.0.0
  # https://pub.dev/packages/bloc_test
  build_runner: ^2.6.0
  # https://pub.dev/packages/build_runner
  # hive_generator: ^2.0.1
  # https://pub.dev/packages/hive_generator
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/flutter_lints
  flutter_launcher_icons: ^0.14.4
  # https://pub.dev/packages/flutter_launcher_icons
  freezed_annotation: ^3.1.0
  # https://pub.dev/packages/freezed_annotation
  flutter_screenutil: ^5.9.3
  # https://pub.dev/packages/flutter_screenutil
  flutter_native_splash: ^2.4.6
  # https://pub.dev/packages/flutter_native_splash


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts: 
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          style: italic
