flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#E9EDFF"  # Background color
  image_path:  "assets/images/blue-logo.png" 
  # adaptive_icon_foreground: "assets/images/reiv9-background.png" # Foreground image
  remove_alpha_ios: true
  background_color_ios: "#E9EDFF"  

flutter_native_splash:
  ios: true
  android: true
  web: false
  color: "#E9EDFF"  
  # background_image: "assets/images/hands.png"
  # branding_mode: bottom
  # branding_bottom_padding: 26
  image: "assets/images/tagplay-logo.png"
  # branding:  "assets/images/brand.png"