name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.7
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.0
  flutter:
    sdk: flutter
  google_sign_in: ^7.1.1
  meta: ^1.16.0
  
  storage_repository: 
    path: ../storage_repository
     

dev_dependencies:
  firebase_auth_platform_interface: ^8.0.0
  firebase_core_platform_interface: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
