// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYbXZRednpkKqEbYztBfrBiLBxfxCVz5I',
    appId: '1:29525038810:android:a925027a98edb8d688b7e3',
    messagingSenderId: '29525038810',
    projectId: 'e-stone2',
    storageBucket: 'e-stone2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD_Hg4etmieNH9QVDe2F0kTAMI8s-GUt4',
    appId: '1:29525038810:ios:c3919da282061c1c88b7e3',
    messagingSenderId: '29525038810',
    projectId: 'e-stone2',
    storageBucket: 'e-stone2.firebasestorage.app',
    androidClientId: '29525038810-ua7ba6vjsj78svufhli0qo6tf63g2oq5.apps.googleusercontent.com',
    iosClientId: '29525038810-u6fsr35e914jklef1b57dn475fksrg3l.apps.googleusercontent.com',
    iosBundleId: 'com.stone.nfc',
  );

}