// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEqb5-TD28JhMDrf6poAPw3w16NcRhBxo',
    appId: '1:1362674123:android:8947381cd6132b81ff364e',
    messagingSenderId: '1362674123',
    projectId: 'driven-development-3e69a',
    storageBucket: 'driven-development-3e69a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdcedQ-DxC3E5AxCHWplXxPEXH64iVp-0',
    appId: '1:1362674123:ios:93fbea1093f0d582ff364e',
    messagingSenderId: '1362674123',
    projectId: 'driven-development-3e69a',
    storageBucket: 'driven-development-3e69a.appspot.com',
    androidClientId: '1362674123-o1in9hln81cetfoh5t5m6ij4o8lr4snm.apps.googleusercontent.com',
    iosClientId: '1362674123-fhhkk69pktorq65nq6f7hm0mmmbru3io.apps.googleusercontent.com',
    iosBundleId: 'com.stone.anaconda',
  );

}