name: storage_repository
description: A repository for handling all data storage including users, videos, NFC tokens, and watch history
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_auth: ^6.0.0
  dartz: ^0.10.1
  # https://pub.dev/packages/dartz

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.2
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  flutter_lints: ^6.0.0

